FROM eclipse-temurin:11-jammy

RUN apt-get update && \
    apt-get install -y git curl build-essential apt-transport-https gnupg && \
    apt-get upgrade -y && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | tee /etc/apt/sources.list.d/sbt.list
RUN echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee /etc/apt/sources.list.d/sbt_old.list
RUN curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --import
RUN chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg

RUN apt-get update && \
    apt-get install -y sbt scala && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /root/.sbt/1.0/plugins && \
    echo 'addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")' > /root/.sbt/1.0/plugins/plugins.sbt

COPY snyk-bulk/scripts/install_snyk.sh /root/install_snyk.sh
RUN chmod +x /root/install_snyk.sh
RUN /root/install_snyk.sh

RUN mkdir -p /usr/local/bin
COPY snyk-bulk/entrypoints/ /usr/local/bin/entrypoints
COPY scripts/run.sh /usr/local/bin/entrypoints/run.sh
RUN chmod +x /usr/local/bin/entrypoints/*

COPY bin/send-metadata /usr/local/bin/metadata/send-metadata

ENV PROJECT_PATH="/opt/security-assistant/repository"
ENV SNYK_RESULTS_DIR=/opt/security-assistant/snyk-bulk-results
ENV API_MAX_RETRIES=3

WORKDIR /opt/security-assistant/repository

ENTRYPOINT ["/usr/local/bin/entrypoints/run.sh", "scala"]
